aosedge/aos_common

- README.md
Signed-off-by: Yevgen Abramov <eabramov84@gmail.com>
> [ci] Fix codecove badge

- wsclient/wsclient.go
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
> [wsclient] Fix wsclient process message

- aostypes/aostypes.go
> [aostype] Add board config structures

- api/cloudprotocol/cloudprotocol.go
> [cloudprotocol] Rename users to subjects in sd request

- utils/fs/fs.go
- utils/fs/fs_test.go
> [fs] Add function to get available size on partition

- image/image.go
> [image] Move imageutils from sm to common

- .golangci.yml
- spaceallocator/spaceallocator.go
- spaceallocator/spaceallocator_test.go
- utils/fs/fs.go
- utils/fs/fs_test.go
Disk manager handles disk space allocation. It will be used by servicemanager, layermanager and downloader.
layermanager usage example: 
```go
func New(
config *config.Config, layerStorage LayerStorage) (layermanager *LayerManager, err error) {
if layermanager.layerAllocator, err = spaceallocator.New(
layermanager.layersDir, 100, layermanager.removeLayer); err != nil {
return aoserrors.Wrap(err)
}
if layermanager.extractAllocator, err = spaceallocator.NewStorage(layermanager.extractDir, 100, nil); err != nil {
return aoserrors.Wrap(err)
}
if layermanager.downloadAllocator, err = spaceallocator.NewStorage(layermanager.downloadDir, 100, nil); err != nil {
return aoserrors.Wrap(err)
}
}
func (layermanager *LayerManager) RemoveLayer(digest string) error {
... …
```
> Space allocator

- image/image_test.go
> Create UT for GetUncompressedTarContentSize

- wsserver/wsserver.go
> [wsserver] Do not log error in case of graceful sutdown

- aostypes/aostypes.go
- aostypes/aostypes_test.go
> [aostypes] Support ISO8601 fro duration format

- aostypes/aostypes.go
- aostypes/aostypes_test.go
> [aostypes] Support ISO8601 for duration format

- aostypes/aostypes.go
> [aostypes] Add node config to board config struct

- aostypes/aostypes.go
- api/cloudprotocol/cloudprotocol.go
> [aostypes,cloudprotocol] Rename board to unit config

- api/cloudprotocol/cloudprotocol.go
> [cloudprotocol] Update API v5 to support multinode

- aostypes/aostypes.go
> Add runner filed to ServiceConfig 

- aostypes/aostypes.go
> [aostype] Change nodeID to nodeType in unitconfig

- api/cloudprotocol/cloudprotocol.go
- api/cloudprotocol/cloudprotocol_test.go
- resourcemonitor/resourcemonitor.go
- resourcemonitor/resourcemonitor_internal_test.go
- utils/pbconvert/pbconvert.go
> [cloudprotocol] Change log types

- api/cloudprotocol/cloudprotocol.go
> [cloudprotocol] Add Received message structure

- api/cloudprotocol/cloudprotocol.go
> Changed name of the field in PushLog

- api/cloudprotocol/cloudprotocol.go
- resourcemonitor/resourcemonitor.go
- resourcemonitor/resourcemonitor_internal_test.go
> [cloudprotocol,resourcemonitor] Rename type to types

- api/cloudprotocol/cloudprotocol.go
> Change fields in PushLog

- api/cloudprotocol/cloudprotocol.go
> Make ErrorInfo field optional in type PushLog

- spaceallocator/spaceallocator.go
- spaceallocator/spaceallocator_test.go
> Fix problem incorrect remove outdated items

- image/image.go
- image/image_test.go
This param adds O_DIRECT flag to destination file. This option increases write speed in some cases.
> [image] Add direct param for copying to device

- aostypes/aostypes.go
- utils/semverutils/semverutils.go
- utils/semverutils/semverutils_test.go
This flag indicated that we should not take into account resources when scheduling instance.
> [aostypes] Add SkipResourceLimits flag to service config

- aostypes/aostypes.go
These changes causes wrong marshaling, suppress warning instead of changing interface.
> [aostypes] Revert back changing marshal interface for time and duration
